version: "3.9"

services:
  db:
    image: postgres:15
    container_name: meu-postgres
    environment:
      POSTGRES_USER: meuusuario
      POSTGRES_PASSWORD: minhasenha
      POSTGRES_DB: meubanco
    ports:
      - "5433:5432"   # porta do host para acessar o banco, se necess√°rio
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  backend:
    build: ./eds_backend
    container_name: meu-backend
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=meuusuario
      - DB_PASSWORD=minhasenha
      - DB_NAME=meubanco
    depends_on:
      - db
    entrypoint: ["/entrypoint.sh"]
    restart: always

  frontend:
    build: ./ecole-des-sables-react
    container_name: meu-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always

volumes:
  postgres_data:
